# encoding: utf-8 #
"""
==========
File Name:              New                    
Author:                 Oscar Fan
Date:                   2021/12/26
                        
==========
"""
import random as r
from turtle import *


class Main:
    def __init__(self):
        self.width, self.height = 1000, 600
        self.screen = Screen()
        title("祝你圣诞快乐")
        bgcolor("black")
        speed("fastest")
        setup(600, 600, startx=None, starty=None)
        pencolor("green")
        pensize(10)
        penup()
        hideturtle()
        goto(0, 150)
        showturtle()
        pendown()
        shape(name="classic")

    def first_floor_tree(self):
        seth(-120)
        for i in range(10):
            fd(12)
            right(2)
        penup()
        goto(0, 150)
        seth(-60)
        pendown()
        for i in range(10):
            fd(12)
            left(2)
        seth(-150)
        penup()
        fd(10)
        pendown()
        for i in range(5):
            fd(10)
            right(15)
        seth(-150)
        penup()
        fd(8)
        pendown()
        for i in range(5):
            fd(10)
            right(15)
        seth(-155)
        penup()
        fd(5)
        pendown()
        for i in range(5):
            fd(7)
            right(15)

    def second_floor_tree(self):
        penup()
        goto(-55, 34)
        pendown()
        seth(-120)
        for i in range(10):
            fd(8)
            right(5)
        penup()
        goto(50, 35)
        seth(-60)
        pendown()
        for i in range(10):
            fd(8)
            left(5)
        seth(-120)
        penup()
        fd(10)
        seth(-145)
        pendown()
        for i in range(5):
            fd(10)
            right(15)
        penup()
        fd(10)
        seth(-145)
        pendown()
        for i in range(5):
            fd(12)
            right(15)
        penup()
        fd(8)
        seth(-145)
        pendown()
        for i in range(5):
            fd(10)
            right(15)
        penup()
        seth(-155)
        fd(8)
        pendown()
        for i in range(5):
            fd(11)
            right(15)

    def third_floor_tree(self):
        penup()
        goto(-100, -40)
        seth(-120)
        pendown()
        for i in range(10):
            fd(6)
            right(3)
        penup()
        goto(80, -39)
        seth(-50)
        pendown()
        for i in range(10):
            fd(6)
            left(3)
        seth(-155)
        penup()
        fd(10)
        pendown()
        for i in range(5):
            fd(8)
            right(10)
        penup()
        fd(8)
        seth(-145)
        pendown()
        for i in range(7):
            fd(8)
            right(10)
        penup()
        fd(8)
        seth(-145)
        pendown()
        for i in range(7):
            fd(7)
            right(10)
        penup()
        fd(8)
        seth(-145)
        pendown()
        for i in range(7):
            fd(7)
            right(10)
        penup()
        fd(8)
        seth(-140)
        pendown()
        for i in range(7):
            fd(6)
            right(10)

    def fourth_floor_tree(self):
        penup()
        goto(-120, -95)
        seth(-130)
        pendown()
        for i in range(7):
            fd(10)
            right(5)
        penup()
        goto(100, -95)
        seth(-50)
        pendown()
        for i in range(7):
            fd(10)
            left(5)
        penup()
        seth(-120)
        fd(10)
        seth(-155)
        pendown()
        for i in range(6):
            fd(8)
            right(10)
        penup()
        seth(-160)
        fd(10)
        seth(-155)
        pendown()
        for i in range(6):
            fd(8)
            right(10)
        penup()
        seth(-160)
        fd(10)
        seth(-155)
        pendown()
        for i in range(6):
            fd(8)
            right(10)
        penup()
        seth(-160)
        fd(10)
        seth(-160)
        pendown()
        for i in range(6):
            fd(8)
            right(10)
        penup()
        seth(-160)
        fd(10)
        seth(-160)
        pendown()
        for i in range(6):
            fd(8)
            right(10)
        penup()
        seth(-160)
        fd(10)
        seth(-165)
        pendown()
        for i in range(5):
            fd(10)
            right(11)

    def wood(self):
        pencolor("#8B4513")
        penup()
        goto(-70, -165)
        seth(-85)
        pendown()
        for i in range(3):
            fd(5)
            left(3)
        penup()
        goto(70, -165)
        seth(-95)
        pendown()
        for i in range(3):
            fd(5)
            right(3)
        seth(-170)
        penup()
        fd(10)
        pendown()
        pendown()
        for i in range(10):
            fd(12)
            right(2)

    def snow(self):
        pencolor("#DCDCDC")
        penup()
        goto(70, -165)
        pendown()
        seth(-90)
        pensize(8)
        circle(-20, 90)
        penup()
        goto(30, -185)
        pendown()
        seth(-180)
        pensize(8)
        fd(40)
        penup()
        goto(-5, -170)
        pendown()
        seth(-180)
        pensize(8)
        fd(35)

    def guest(self, x, y, z):
        penup()
        goto(x, y)
        seth(-z)
        pendown()
        for angel in range(5):
            fd(10)
            right(10)

    def guet(self, x, y, z):
        penup()
        goto(x, y)
        seth(-z)
        pendown()
        for angel in range(5):
            fd(10)
            left(10)

    def qu(self, x, y, z):
        penup()
        goto(x, y)
        seth(-z)
        pendown()
        for angel in range(5):
            fd(6)
            right(10)
        seth(-150)
        fd(20)

    def hdj(self, x, y):
        # 中蝴蝶结
        penup()
        pencolor("#f799e6")
        goto(x, y)
        seth(80)
        pendown()
        pensize(2)
        circle(5)
        seth(10)
        fd(15)
        seth(120)
        fd(20)
        seth(240)
        fd(20)
        seth(180)
        fd(20)
        seth(-60)
        fd(20)
        seth(50)
        fd(20)
        seth(-40)
        fd(30)
        seth(-130)
        fd(5)
        seth(135)
        fd(30)
        seth(-60)
        fd(30)
        seth(-150)
        fd(6)
        seth(110)
        fd(30)

    def uit(self, x, y):
        # 小蝴蝶结
        penup()
        pencolor("#f799e6")
        goto(x, y)
        pendown()
        pensize(2)
        circle(5)
        seth(-10)
        fd(15)
        seth(90)
        fd(15)
        seth(200)
        fd(15)
        seth(160)
        fd(15)
        seth(-90)
        fd(15)
        seth(10)
        fd(15)
        seth(-60)
        fd(20)
        seth(-180)
        fd(5)
        seth(110)
        fd(20)
        seth(-90)
        fd(20)
        seth(-180)
        fd(6)
        seth(70)
        fd(15)
        hideturtle()

    def yut(self, x, y, z):
        penup()
        goto(x, y)
        pendown()
        seth(z)
        for po in range(5):
            fd(4)
            left(36)

    def butterflies(self):
        seth(0)
        self.uit(40, -150)
        self.hdj(-80, -110)
        self.yut(-67, -105, 120)
        self.yut(-86, -113, 150)
        self.hdj(40, -40)
        self.yut(52, -35, 130)
        self.yut(34, -45, 160)
        seth(0)
        self.uit(-20, -50)
        self.yut(-4, -50, 100)
        self.yut(-20, -50, 120)
        self.hdj(-30, 30)
        self.yut(-15, 35, 130)
        self.yut(-40, 30, 180)
        self.uit(30, 70)
        self.yut(45, 70, 100)
        self.yut(30, 70, 120)

    def iou(self, x, y, z):
        penup()
        goto(x, y)
        pencolor("red")
        pendown()
        seth(z)
        for po in range(10):
            fd(4)
            left(18)

    def hat(self):
        seth(-20)
        pensize(2)
        penup()
        goto(-30, -120)
        pencolor("white")
        pendown()
        fillcolor("white")
        begin_fill()
        fd(30)
        circle(4, 180)
        fd(30)
        circle(4, 180)
        end_fill()
        penup()
        goto(-25, -115)
        seth(75)
        pendown()
        fillcolor("red")
        begin_fill()
        for i in range(5):
            fd(6)
            right(20)
        seth(-10)
        for i in range(5):
            fd(8)
            right(15)
        seth(145)
        for i in range(5):
            fd(5)
            left(2)
        seth(90)
        for i in range(5):
            fd(1)
            left(2)
        seth(-90)
        for i in range(4):
            fd(4)
            right(6)
        seth(161)
        fd(30)
        end_fill()
        pensize(1)
        pencolor("white")

    def koc(self, x, y, size):
        pensize(2)
        pencolor("yellow")
        penup()
        goto(x, y)
        pendown()
        begin_fill()
        fillcolor("yellow")
        for i in range(5):
            left(72)
            fd(size)
            right(144)
            fd(size)
        end_fill()

    def stars(self):
        seth(-15)
        self.koc(-120, -70, 10)
        seth(10)
        self.koc(100, -20, 10)
        seth(-10)
        self.koc(10, 40, 10)
        seth(30)
        self.koc(-80, 60, 10)
        self.koc(100, -150, 10)
        self.koc(-140, -150, 10)
        self.koc(20, 120, 10)
        self.koc(-5, 180, 20)

    def socks(self):
        seth(-20)
        pensize(2)
        penup()
        goto(-20, 80)
        pencolor("white")
        pendown()
        begin_fill()
        fillcolor("white")
        fd(25)
        circle(4, 180)
        fd(25)
        circle(4, 180)
        end_fill()
        penup()
        goto(-15, 80)
        pendown()
        begin_fill()
        fillcolor("red")
        seth(-120)
        fd(20)
        seth(150)
        fd(5)
        circle(7, 180)
        fd(15)
        circle(5, 90)
        fd(30)
        seth(160)
        fd(18)
        end_fill()
        penup()
        seth(0)
        goto(70, -240)
        color("#F5E16F")
        write("祝你圣诞快乐", align="right", font=("黑体", 16, "bold"))
        pendown()

    def snow_is_moving(self):
        self.screen.delay(0)  # 这里要设为0，否则很卡
        t = Turtle(visible=False, shape='circle')
        t.pencolor("white")
        t.fillcolor("white")
        t.penup()
        t.setheading(-90)
        t.goto(r.randint(-self.width / 2, self.width / 2), self.height / 2)
        stars = []
        for i in range(200):
            star = t.clone()
            s = r.random() / 3
            star.shapesize(s, s)
            star.speed(int(s * 10))
            star.setx(r.randint(-self.width / 2, self.width / 2))
            star.sety(self.height / 2 + r.randint(1, self.height))
            star.showturtle()
            stars.append(star)
        while True:
            for star in stars:
                star.sety(star.ycor() - 8 * star.speed())
                if star.ycor() < -self.height / 2:
                    star.hideturtle()
                    star.setx(r.randint(-self.width / 2, self.width / 2))
                    star.sety(self.height / 2 + r.randint(1, self.height))
                    star.showturtle()

    def run(self):
        self.first_floor_tree()
        self.second_floor_tree()
        self.third_floor_tree()
        self.fourth_floor_tree()
        self.wood()
        self.snow()
        self.butterflies()
        self.hat()
        self.stars()
        self.socks()
        self.snow_is_moving()
        hideturtle()
        done()


ct = Main()
ct.run()
